### ISSUE TITLE
也许你还可以加一个所在VLAN ID上去

### ISSUE THREAD

**Issue by hel2o** [hongfeioo/UserDeviceTracker#1]
![图片](https://user-images.githubusercontent.com/14226648/64930160-9fbe0000-d860-11e9-8ef2-991b3ca22747.png)
再就是为何你都用了golang前端查询为何还搞一个php进来，这不更复杂吗？直接使用golang的http不更好呀

**Comment by hongfeioo** [comment]
> ![图片](https://user-images.githubusercontent.com/14226648/64930160-9fbe0000-d860-11e9-8ef2-991b3ca22747.png)
> 再就是为何你都用了golang前端查询为何还搞一个php进来，这不更复杂吗？直接使用golang的http不更好呀

前端的问题关注的少
